#!/usr/bin/env bash
#fizz buzz
for ((i = 1; i < 101; i++))
do
	if [ $(( i % 3 )) -eq 0 ] && [ $(( i % 5 )) -eq 0 ]; then 
		echo "FizzBuzz"

	else 
		if [ $(( i % 3 )) -eq 0 ]; then 
			echo "Fizz"

		fi

		if [ $(( i % 5 )) -eq 0 ]; then
			echo "Buzz"

		fi

		if [ $(( i % 3 )) -ne 0 ] && [ $(( i % 5 )) -ne 0 ]; then
			echo "$i"

		fi
	fi
done
